# Generated by Django 2.1 on 2020-03-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('patient_age', models.IntegerField()),
                ('appointment_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=100)),
                ('doctor_pic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=250)),
                ('Fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Categorypic', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.Service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.Doctor'),
        ),
    ]
