# Generated by Django 2.1 on 2020-03-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Categorypic',
            new_name='category_pic',
        ),
    ]
